services:
  db:
    image: postgres:16
    container_name: db 
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-cherrytree}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    container_name: backend 
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend

    container_name: frontend  
    env_file:
      - .env
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app           # Bind mount: Syncs host source code to container
      - /app/node_modules # Anonymous volume: Prevents overriding container modules
    environment:
      - WATCHPACK_POLLING=true  # Fallback watcher engine variable for Webpack/CRA
      - CHOKIDAR_USEPOLLING=true # Fallback watcher engine variable for older setups

volumes:
  db_data:
